site_name: Ueui的文档站
site_url: https://gh3406286420.github.io/ueui
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

# 👇 左侧菜单栏（你可以自由增删）
nav:
  - 首页: index.md
  - 关于: deploy-guide.md
  - 工具: tool.md
  - 文章:
    - 学习日志:
        - 抢单接口压测过程: txt1.md
        - 以目标为导向: txt2.md
        - 前端部署记录: txt3.md
        - 压缩Java内存: txt4.md
        - 传播App经验: txt5.md
        - 粗浅理解深度学习: txt6.md
  - 算法:
      - 自制Skill进行代码转化的情况: txt10.md
      - 像写Java一样写C++: txt7.md
      - 像写Java/cpp一样写 Python: txt8.md
      - 像写Python一样写Go-AI生成: txt9.md





markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences